### ISSUE TITLE
Clicking on file keys in the file browser behaves as they were directories

### ISSUE THREAD

**Issue by tib** [FeatherCMS/feather#52] opened 2021-01-07 11:50 UTC
Clicking on a key of a file should open the preview window instead of navigating into a sub-directory.

**Comment by fdstevex** [comment] 2021-01-24 23:34
Taking a look at this - the issue is that the controller doesn't know if the item is directory or a file.  All that's returned from LiquidKit's `FileStorage.list` is the name.

One option would be to have an additional `list` method that works something like NSFileManager's `contentsOfDirectoryAtURL:includingPropertiesForKeys...` or `enumeratorAtURL: includingPropertiesForKeys...` that lets the caller indicate what they're interested in.  I could see wanting the file browser to show the file size, date and maybe other metadata in addition to just the name.

Curious if that's what you were expecting as a fix for this?

**Comment by tib** [comment] 2021-01-28 08:57
As a quick&dirty solution I was thinking about simply checking the name of the item, if it contains an extension then it's a file.

On the long term of course your solution would be the right way to go. :)

**Closed** 2021-01-29 10:14 UTC
Labels: admin, bug, file, good first issue, help wanted
